### ISSUE TITLE
New UI: Double callbacks happening in legacy content (2018.2)

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#1126]
**Describe the bug**
Carl observed it happening while moderating items, and editing items while in moderation. But it would likely happen elsewhere too.

@doolse fixed this in 2018.2 (https://github.com/apereo/openEQUELLA/commit/1d96348d9b6bbca6541f2c364f5c6801ee011a04). But it looks like it would have to be fixed slightly differently in 2019.1.

**To Reproduce**
Steps to reproduce the behaviour:
https://drive.google.com/open?id=1sJNdfv4qS35xdhU_huBvqpvBHxvgSzcw

**Stacktrace**

```
Caused by: com.tle.web.sections.SectionsRuntimeException: Only one callback supported currently
     at com.tle.web.sections.standard.model.HtmlComponentState.addRendererCallback(HtmlComponentState.java:231)
     at com.tle.web.sections.standard.AbstractRenderedComponent.renderHtml(AbstractRenderedComponent.java:226)
     at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50)
     at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82)
     at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24)
     at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:574)
     at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:469)
     at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:244)
     at com.tle.web.sections.SectionWriter.processEvent(SectionWriter.java:452)
     at com.tle.web.sections.equella.freemarker.ChooseRenderer.getSectionRenderable(ChooseRenderer.java:101)
     ... 179 more 
```

**Platform:**

- OpenEquella Version: 2018.2
- OS: Windows 10
- Browser chrome

**Comment by edalex-ian** [comment]
This is fixed and tested isn't it @mrblippy
